
services:
  ollama:
    image: ollama/ollama
    container_name: ollama-container
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    runtime: nvidia  # Использование GPU runtime
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Указываем все доступные GPU

  postgres:
    image: postgres
    container_name: postgres-container
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "nutrition"
      POSTGRES_USER: "db_username"
      POSTGRES_PASSWORD: "db_password"
    ports:
      - "5432:5432"

  ai:
    build:
      context: ./
      dockerfile: ai/Dockerfile
    container_name: ai-container
    working_dir: /ai
    volumes:
      - ./ai/:/ai
    ports:
      - "8501:8501"

  macos:
    build:
      context: ./
      dockerfile: macos/Dockerfile
    container_name: macos-container
    working_dir: /macos
    volumes:
      - ./macos/:/macos
    environment:
      VERSION: "Sequoia"
      KVM: N
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp

  bot:
    build:
      context: ./
      dockerfile: bot/Dockerfile
    container_name: bot-container
    working_dir: /bot
    volumes:
      - ./:/bot
    env_file:
      - .env

volumes:
  ollama:
  pgdata:
